server.port: 8081
spring:
  application:
    name: reagan-feign-client
  profiles:
    active: default
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848