version: '3.7'
services:
  nacos:
    # mac m1 arm版
    #image:  nacos/nacos-server:v2.1.1-slim
    image: nacos/nacos-server:latest
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - MODE=standalone
