version: "3.7"
services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - 8500:8500
    command: ["consul","agent","-server","-bootstrap","-data-dir","/consul","-ui","-bind","127.0.0.1","-client","0.0.0.0"]