version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.17.2
    container_name: elasticsearch
    networks:
      - host
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #设置使用jvm内存大小
    volumes:
      - /tmp/reagan/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /tmp/reagan/elk/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
# 不知道为啥不能用
#    command:
#      - /bin/bash
#      - ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.2/elasticsearch-analysis-ik-7.17.2.zip
  kibana:
    image: kibana:7.17.2
    container_name: kibana
    networks:
      - host
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - "5601:5601"
  logstash:
    image: logstash:7.17.2
    container_name: logstash
    networks:
      - host
    volumes:
      # 记住要手动创建logstash.conf，看README.md
      - /tmp/reagan/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - "4560:4560"
# 不知道为啥不能用
#    command:
#      - /bin/bash
#      - logstash-plugin install logstash-codec-json_lines
networks:
  host: