app:
  author: reagan
server.port: 8080
spring:
  application:
    name: reagan_provider
  profiles:
    active: default
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

