app:
  author: reagan
server.port: 8081
spring:
  application:
    name: reagan-consumer
  profiles:
    active: default
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s
#management:
#  endpoints.web.exposure.include: *
#  endpoint.health.show-details: always

